kumuluzee:
  name: halal-place-catalog-service
  env:
    name: dev
  version: 1.0
  server:
    base-url: https://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/HalalPlaceMetadataDS
      #connection-url: jdbc:postgresql://localhost:5432/halal_place_metadata
      connection-url: jdbc:postgresql://suleiman.db.elephantsql.com:5432/gegqziaq
      username: gegqziaq
      password: RMNRyMoKcRWdLtfUSOp_96M0U0F9B6IB
      #username: postgres
      #password: projectRSOhFood
      max-pool-size: 20
  rest-properties:
    maintenance-mode: false


# docker run -d --name pg-halal-place-metadata -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=projectRSOhFood -e POSTGRES_DB=halal_place_metadata -p 5432:5432 postgres:13
# docker run -p 8080:8080 --network rso -e KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://localhost:5432/halal_place_metadata rso-dn